language: java
jdk:
  - oraclejdk8
  - oraclejdk7
#  - oraclejdk6
#  - oraclejdk5
  - openjdk7
  - openjdk6
#  - openjdk5

os:
  - linux
  - osx
  - windows

  # Fix OpenJDK builds
  # https://github.com/travis-ci/travis-ci/issues/5227
sudo: false

install: mvn install -DskipTests=true -B
script: mvn test -B

after_success:
  - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:cobertura
