language: java
sudo: false

install:
  - 

matrix:
  fast_finish: true
  include:
    # unit tests (openjdk7, oraclejdk7 and oraclejdk8)
    - jdk: openjdk7
      env: DESC="tests" CMD="mvn clean integration-test failsafe:verify" COVERAGE_CMD=""
    - jdk: oraclejdk7
      env: DESC="tests" CMD="mvn clean integration-test failsafe:verify" COVERAGE_CMD=""
    - jdk: oraclejdk8
      env: DESC="tests" CMD="mvn clean integration-test failsafe:verify" COVERAGE_CMD=""

    # checkstyle (openjdk7, oraclejdk7 and oraclejdk8)
    - jdk: openjdk7
      env:
        - DESC="checkstyle"
        - CMD="mvn clean verify -DskipTests -DskipITs -Dpmd.skip=true -Dfindbugs.skip=true -Dcobertura.skip=true"
        - COVERAGE_CMD=""
    - jdk: oraclejdk7
      env:
        - DESC="checkstyle"
        - CMD="mvn clean verify -DskipTests -DskipITs -Dpmd.skip=true -Dfindbugs.skip=true -Dcobertura.skip=true"
        - COVERAGE_CMD=""
    - jdk: oraclejdk8
      env:
        - DESC="checkstyle"
        - CMD="mvn clean verify -DskipTests -DskipITs -Dpmd.skip=true -Dfindbugs.skip=true -Dcobertura.skip=true"
        - COVERAGE_CMD=""

    # cobertura and coveralls (oraclejdk8)
    - jdk: oraclejdk8
      env:
        - DESC="cobertura and coveralls"
        - CMD="mvn clean cobertura:check cobertura:cobertura"
        - COVERAGE_CMD="bash <(curl -s https://codecov.io/bash)"
    # findbugs and pmd (oraclejdk8)
    - jdk: oraclejdk8
      env:
        - DESC="findbugs and pmd"
        - CMD="mvn clean compile pmd:check findbugs:check"
        - COVERAGE_CMD=""

    # site (oraclejdk8 as 'site' success is required to be sure that on release time all will be ok, admins will use oracle8 version)
    - jdk: oraclejdk8
      env:
        - DESC="site"
        - CMD1="mvn clean site -Dlinkcheck.skip=true -Dmaven.javadoc.skip=true -DskipTests -DskipITs "
        - CMD2=" -Dpmd.skip=true -Dfindbugs.skip=true -Dcobertura.skip=true -Dcheckstyle.ant.skip=true"
        - CMD=$CMD1$CMD2
        - COVERAGE_CMD=""
    # assembly (oraclejdk8)
    - jdk: oraclejdk8
      env:
        - DESC="assembly"
        - CMD1="mvn clean install -Passembly -DskipTests -DskipITs -Dcobertura.skip=true"
        - CMD2=" -Dpmd.skip=true -Dfindbugs.skip=true -Dcheckstyle.ant.skip=true"
        - CMD=$CMD1$CMD2
        - COVERAGE_CMD=""
    # nemo.sonarqube.com (oraclejdk7)
    - jdk: oraclejdk7
      env:
        - DESC="nemo.sonarqube.com"
        - CMD1="mvn clean install cobertura:cobertura -Dcobertura.report.format=xml "
        - CMD2=" -Dmaven.test.failure.ignore=true -V -Dcheckstyle.skip=true "
        - CMD3=" -Dpmd.skip=true -Dcheckstyle.ant.skip=true"
        - CMD=$CMD1$CMD2$CMD3
        - COVERAGE_CMD=""

    # NoErrorTest - Orekit (oraclejdk8)
    - jdk: oraclejdk8
      env:
        - DESC="NoErrorTest - Orekit"
        - CMD1="git clone https://github.com/CS-SI/Orekit.git && cd Orekit && git checkout bc527a1 "
        - CMD2=" && sed -i 's/<orekit\.checkstyle\.version>6\.6</<orekit.checkstyle.version>6.9-SNAPSHOT</' pom.xml "
        - CMD3=" && cd .. && mvn clean install -Passembly -DskipTests -DskipITs -Dcobertura.skip=true "
        - CMD4="    -Dpmd.skip=true -Dfindbugs.skip=true -Dcheckstyle.ant.skip=true "
        - CMD5=" && cd Orekit && mvn compile checkstyle:check"
        - CMD=$CMD1$CMD2$CMD3$CMD4$CMD5
        - COVERAGE_CMD=""

    # NoExceptiontest - Checkstyle, sevntu-checkstyle (oraclejdk8)
    - jdk: oraclejdk8
      env:
        - DESC="NoExceptionTest - Checkstyle, sevntu-checkstyle"
        - CMD1="git clone https://github.com/checkstyle/contribution && cd contribution/checkstyle-tester "
        - CMD2=" && sed -i 's/^guava/#guava/' projects-for-travis.properties "
        - CMD3=" && sed -i 's/#checkstyle/checkstyle/' projects-for-travis.properties "
        - CMD4=" && sed -i 's/#sevntu-checkstyle/sevntu-checkstyle/' projects-for-travis.properties "
        - CMD5=" && sed -i 's/projects-to-test-on.properties/projects-for-travis.properties/' launch.sh "
        - CMD6=" && cd ../../ && mvn clean install -DskipTests -DskipITs -Dcobertura.skip=true "
        - CMD7="    -Dpmd.skip=true -Dfindbugs.skip=true -Dcheckstyle.ant.skip=true "
        - CMD8=" && cd contribution/checkstyle-tester "
        - CMD9=" && ./launch.sh -Dcheckstyle.config.location=checks-nonjavadoc-error.xml"
        - CMD=$CMD1$CMD2$CMD3$CMD4$CMD5$CMD6$CMD7$CMD8$CMD9
        - COVERAGE_CMD=""
    # NoExceptiontest - Guava (oraclejdk8)
    - jdk: oraclejdk8
      env:
        - DESC="NoExceptionTest - Guava"
        - CMD1="git clone https://github.com/checkstyle/contribution && cd contribution/checkstyle-tester"
        - CMD2=" && sed -i 's/^guava/#guava/' projects-for-travis.properties"
        - CMD3=" && sed -i 's/#guava/guava/' projects-for-travis.properties"
        - CMD4=" && sed -i 's/projects-to-test-on.properties/projects-for-travis.properties/' launch.sh"
        - CMD5=" && cd ../../ && mvn clean install -DskipTests -DskipITs -Dcobertura.skip=true"
        - CMD6="    -Dpmd.skip=true -Dfindbugs.skip=true -Dcheckstyle.ant.skip=true "
        - CMD7=" && cd contribution/checkstyle-tester "
        - CMD8=" && ./launch.sh -Dcheckstyle.config.location=checks-nonjavadoc-error.xml"
        - CMD=$CMD1$CMD2$CMD3$CMD4$CMD5$CMD6$CMD7$CMD8
        - COVERAGE_CMD=""
    # NoExceptionTest - Hibernate ORM (oraclejdk8)
    - jdk: oraclejdk8
      env:
        - DESC="NoExceptionTest - Hibernate ORM"
        - CMD="git clone https://github.com/checkstyle/contribution && cd contribution/checkstyle-tester && sed -i 's/^guava/#guava/' projects-for-travis.properties && sed -i 's/#hibernate-orm/hibernate-orm/' projects-for-travis.properties && sed -i 's/projects-to-test-on.properties/projects-for-travis.properties/' launch.sh && cd ../../ && mvn clean install -DskipTests -DskipITs -Dpmd.skip=true -Dfindbugs.skip=true -Dcobertura.skip=true -Dcheckstyle.ant.skip=true && cd contribution/checkstyle-tester && ./launch.sh -Dcheckstyle.config.location=checks-nonjavadoc-error.xml"
        - COVERAGE_CMD=""
    # NoExceptionTest - FindBugs (oraclejdk8)
    - jdk: oraclejdk8
      env:
        - DESC="NoExceptionTest - FindBugs"
        - CMD="git clone https://github.com/checkstyle/contribution && cd contribution/checkstyle-tester && sed -i 's/^guava/#guava/' projects-for-travis.properties && sed -i 's/#findbugs/findbugs/' projects-for-travis.properties && sed -i 's/projects-to-test-on.properties/projects-for-travis.properties/' launch.sh && cd ../../ && mvn clean install -DskipTests -DskipITs -Dpmd.skip=true -Dfindbugs.skip=true -Dcobertura.skip=true -Dcheckstyle.ant.skip=true && cd contribution/checkstyle-tester && ./launch.sh -Dcheckstyle.config.location=checks-nonjavadoc-error.xml"
        - COVERAGE_CMD=""
    # NoExceptionTest - Pmd,elasticsearch,lombok-ast (oraclejdk8)
    - jdk: oraclejdk8
      env:
        - DESC="NoExceptionTest - Pmd,elasticsearch,lombok-ast"
        - CMD="git clone https://github.com/checkstyle/contribution && cd contribution/checkstyle-tester && sed -i 's/^guava/#guava/' projects-for-travis.properties && sed -i 's/#pmd/pmd/' projects-for-travis.properties && sed -i 's/#elasticsearch/elasticsearch/' projects-for-travis.properties && sed -i 's/#lombok-ast/lombok-ast/' projects-for-travis.properties && sed -i 's/projects-to-test-on.properties/projects-for-travis.properties/' launch.sh && cd ../../ && mvn clean install -DskipTests -DskipITs -Dpmd.skip=true -Dfindbugs.skip=true -Dcobertura.skip=true -Dcheckstyle.ant.skip=true && cd contribution/checkstyle-tester && ./launch.sh -Dcheckstyle.config.location=checks-nonjavadoc-error.xml"
        - COVERAGE_CMD=""
    # NoExceptionTest - RxJava,java-design-patterns,MaterialDesignLibrary,apache-ant,apache-jsecurity,android-launcher (oraclejdk8)
    - jdk: oraclejdk8
      env:
        - DESC="NoExceptionTest - RxJava,java-design-patterns,MaterialDesignLibrary,apache-ant,apache-jsecurity,android-launcher"
        - CMD="git clone https://github.com/checkstyle/contribution && cd contribution/checkstyle-tester && sed -i 's/^guava/#guava/' projects-for-travis.properties && sed -i 's/#RxJava/RxJava/' projects-for-travis.properties && sed -i 's/#java-design-patterns/java-design-patterns/' projects-for-travis.properties && sed -i 's/#MaterialDesignLibrary/MaterialDesignLibrary/' projects-for-travis.properties && sed -i 's/#apache-ant/apache-ant/' projects-for-travis.properties && sed -i 's/#apache-jsecurity/apache-jsecurity/' projects-for-travis.properties && sed -i 's/#android-launcher/android-launcher/' projects-for-travis.properties && sed -i 's/projects-to-test-on.properties/projects-for-travis.properties/' launch.sh && cd ../../ && mvn clean install -DskipTests -DskipITs -Dpmd.skip=true -Dfindbugs.skip=true -Dcobertura.skip=true -Dcheckstyle.ant.skip=true && cd contribution/checkstyle-tester && ./launch.sh -Dcheckstyle.config.location=checks-nonjavadoc-error.xml"
        - COVERAGE_CMD=""
    # NoExceptionTest - Spring (oraclejdk8)
    - jdk: oraclejdk8
      env:
        - DESC="NoExceptionTest - Spring"
        - CMD1="git clone https://github.com/checkstyle/contribution && cd contribution/checkstyle-tester"
        - CMD2=" && sed -i 's/^guava/#guava/' projects-for-travis.properties "
        - CMD3=" && sed -i 's/#spring-framework/spring-framework/' projects-for-travis.properties "
        - CMD4=" && sed -i 's/projects-to-test-on.properties/projects-for-travis.properties/' launch.sh "
        - CMD5=" && cd ../../ && mvn clean install -DskipTests -DskipITs -Dcobertura.skip=true "
        - CMD6=" -Dpmd.skip=true -Dfindbugs.skip=true -Dcheckstyle.ant.skip=true "
        - CMD7=" && cd contribution/checkstyle-tester "
        - CMD8=" && travis_wait ./launch.sh -Dcheckstyle.config.location=checks-nonjavadoc-error.xml"
        - CMD=$CMD1$CMD2$CMD3$CMD4$CMD5$CMD6$CMD7$CMD8
        - COVERAGE_CMD=""
    # NoExceptionTest - Hbase (oraclejdk8)
    - jdk: oraclejdk8
      env:
        - DESC="NoExceptionTest - Hbase"
        - CMD="git clone https://github.com/checkstyle/contribution && cd contribution/checkstyle-tester && sed -i 's/^guava/#guava/' projects-for-travis.properties && sed -i 's/#Hbase/Hbase/' projects-for-travis.properties && sed -i 's/projects-to-test-on.properties/projects-for-travis.properties/' launch.sh && cd ../../ && mvn clean install -DskipTests -DskipITs -Dpmd.skip=true -Dfindbugs.skip=true -Dcobertura.skip=true -Dcheckstyle.ant.skip=true && cd contribution/checkstyle-tester && travis_wait ./launch.sh -Dcheckstyle.config.location=checks-nonjavadoc-error.xml"
        - COVERAGE_CMD=""


script: eval $CMD

after_success:
  - eval $COVERAGE_CMD

cache:
  directories:
  - ~/.m2

branches:
  only:
    - master
