environment:
  matrix:

    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.1"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5.1"
      PYTHON_ARCH: "64"

    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "64"


install:
    - "%PYTHON%\\python.exe -m pip install -r test-requirements.txt"
    - "git submodule update --init typeshed"
    - "%PYTHON%\\python.exe setup.py -q install"

build: off

test_script:
    # Ignore lint (it's run in Travis)
    - "%PYTHON%\\python.exe runtests.py -x lint"

after_test:
  - "%PYTHON%\\python.exe -m pip install wheel"
  - "%PYTHON%\\python.exe setup.py bdist_wheel -p win32"
  - "%PYTHON%\\python.exe setup.py bdist_wheel -p win_amd64"

artifacts:
  - path: dist\*

skip_commits:
  files:
    - docs/**/*
    - '**/*.rst'
    - '**/*.md'
    - .gitignore
    - .runtest_log.json
    - .travis.yml
    - CREDITS
    - LICENSE
