environment:

  global:
    PYTHON: "C:\\conda"
    MINICONDA_VERSION: "3.5.5"
    WITH_COMPILER: "cmd /E:ON /V:ON /C .\\.ci\\appveyor\\run_with_env.cmd"
    NUMPY_VERSION: "1.9.1"

  matrix:
    - PYTHON_VERSION: "2.6"
    - PYTHON_VERSION: "2.7"
    - PYTHON_VERSION: "3.3"
    - PYTHON_VERSION: "3.4"

platform:
  - x64
  - x86

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PLATFORM%"

install:
  - "powershell .\\.ci\\appveyor\\install-miniconda.ps1"
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "conda update --yes conda"
  - "conda create -q --yes -n test python=%PYTHON_VERSION%"
  - "activate test"
  - "python --version"
  - "conda install -q --yes numpy=%NUMPY_VERSION% pip jinja2 scipy nose>=1.3 matplotlib netCDF4 sympy pandas Cython"
  - "pip install wheel"
  - "%WITH_COMPILER% python setup.py install"

build: false

test_script:
  #- "%WITH_COMPILER% python setup.py build_ext --inplace"
  #- "%WITH_COMPILER% python coupled_driver.py"
  - "%WITH_COMPILER% python scripts/test-installed-landlab.py --doctests"

after_test:
  - "%WITH_COMPILER% python setup.py bdist_wheel"

artifacts:
  # Archive the generated conda package in the ci.appveyor.com build report.
  - path: 'dist\*'

deploy:
  provider: FTP
  protocol: ftp
  host: csdms.colorado.edu
  username: anonymous
  password: appveyor@appveyor.com
  folder: incoming/huttone/
  on:
    appveyor_repo_tag: true
